### ISSUE TITLE
Message Field Ghosts over Activities

### ISSUE THREAD

**Issue by ghost** [petersmithca/humhub-basic-chat#18]
When you first load a page containing the shoutbox the text field will duplicate over the activities.
This is just visual, you can't type on it or anything, hence why I said it's a "ghost".

Upon switching tab focus away from and back to the page the issue disappears. This occurs in Chrome.
![text field](https://cloud.githubusercontent.com/assets/16280813/15454435/91d23918-2006-11e6-9c9b-6d421dcaecbf.png)

**Comment by petersmithca** [comment]
Unfortunately, I have very little time these days to work on any outside projects, so this will likely stay unresolved unless someone else has a little time.  Hopefully someone can.
