### ISSUE TITLE
Long users names overlap the time

### ISSUE THREAD

**Issue by ghost** [petersmithca/humhub-basic-chat#19]
In spaces where the chat width is more constrained longer usernames will overlap the time.
![katsu](https://cloud.githubusercontent.com/assets/16280813/15454500/101c3868-2008-11e6-818c-f1577e369d82.jpeg)

**Comment by petersmithca** [comment]
I'm not sure anyway to change that except make the names wrap which might look even worse.  Or truncate them.  Unfortunately, I have very little time these days to work on any outside projects, so this will likely stay unresolved unless someone else has a little time.
