### ISSUE TITLE
Doesn't start error Yii Exception 

### ISSUE THREAD

**Issue by LokyStaz** [petersmithca/humhub-basic-chat#20]
I tried to activated but that give me an error... So I look inside, and all files seems to be made for a folder name "humhubchat" not "basic-chat" and the name and id in json doesn't match aswell !!
So I tried to make all the necessary change, but that style gave me the same error on activation : 

> Exception – yii\base\Exception - Could not find module: humhubchat

And many of the errors point to "protected\humhub\models\Setting.php"

Thanks for any help!

**Comment by petersmithca** [comment]
per the README

Installation
1. Download the module and upload it to your modules directory >
   yourdomain.com>protected>modules
2. Rename module directory basic-chat (May not be required!)
3. Enable module from >Admin>Modules

Doing that it works fine for me in my version.  However I no longer am
doing development on humhub as I do not have the time, so I cannot support
or update this module.

**Comment by LokyStaz** [comment]
I know that... I tried but still doesn't work...

Ok thanks, so I will look to make a new module !!
Thanks for your answer !! have nice time.
