### ISSUE TITLE
License type of humhub-basic-chat ? ( add new features )

### ISSUE THREAD

**Issue by aRandomKiwi** [petersmithca/humhub-basic-chat#21]
Hi,
Could you publicy mention what kind of license are you using for this project ?
It's for adding several features to humhub-chat with my team to make it a real chat module : 
-Private chat
-Offline chat support
-Emoji support
-Space based chat (group chat)
-Notifications
-....
But we only take time for Open Source projects (Mit,Apache, GPL...).

Regards

**Comment by Mariick** [comment]
I have my answer, must be gpl compliant license due tu humhub agpl license:
[https://www.gnu.org/licenses/gpl-faq.html#GPLAndPlugins](https://www.gnu.org/licenses/gpl-faq.html#GPLAndPlugins)
