### ISSUE TITLE
Could not find module

### ISSUE THREAD

**Issue by luketainton** [petersmithca/humhub-basic-chat#22]
When enabling the module, I get an exception - see image.
![exception](https://cloud.githubusercontent.com/assets/22561713/24362580/237ec376-1305-11e7-908a-3daddd922f0b.png)

**Comment by Felli** [comment]
This module isn't for v1.2 or newer, it only works up to v1.1.2 at the moment.

**Comment by bragamiguel** [comment]
Hi Felli, are you planning to release it to v1.2.2? That would be super!

**Comment by Felli** [comment]
Hello @bragamiguel, to answer your question, I have done a lot of work with the module, and have stopped as of [v1.2](https://github.com/GreenMeteor/humhub-BasicChat-module) regarding this project.
