### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by Reuns** [petersmithca/humhub-basic-chat#23]
Since I installed the module, I have an internal error !
I can access to agenda, mail, notifications, user account...
But I can't access to spaces, dashboard and admin pages.

So right know my community is broken, and I don't know how to do to get it back.
As I can't go to the admin page, I'm not able to disable the module.

Please, help me.
https://highscore.gros-boulet.com

**Comment by DarkestEver** [comment]
i am facing the same issue. Need help!!

**Comment by Felli** [comment]
This module is no longer maintained, it isn't recommended using with newer versions of HumHub.
