### ISSUE TITLE
Creates unusable Space Module

### ISSUE THREAD

**Issue by Felli** [petersmithca/humhub-basic-chat#3]
After some testing I noticed that this module creates an unnecessary module in spaces but doesn't work within a space that has enabled the module.
# Example
### Before Enabled

![](http://i.imgur.com/asDxu3y.png)
### After Enabled

![](http://i.imgur.com/HbFdoVr.png)
### Results After Endabled

![screenshot-futayuriverse com 2016-02-15 21-19-36](https://cloud.githubusercontent.com/assets/2011633/13065447/7cb0327e-d42a-11e5-84ec-afe434a5fb8b.png)

**Comment by petersmithca** [comment]
I honestly never realized there were "space" modules before.  Wasn't intended to work in spaces (mainly because they have different size side bars and I don't know css well enough to make a ton of versions).  I'll look into removing from this menu when I get some time

**Comment by petersmithca** [comment]
Hi @Felli , unfortunately my old computer died and I don't yet have my new environment set up. I believe this issue is caused by line 36 of module.php. Could you comment it out by adding // in front of the code and see if this resolves the issue?

**Comment by WebCrew** [comment]
@petersmithca the commenting out solution does work for me.

Note: The new style is 90% responsive and work with different screen resolutions, so it should be no problem now to use the chat also within smaller panels. Its not perfect so far but with one of the next style updates I try to make the user panel "off canvas" with a small button to open and close it. This should help to solv the little issue.

**Comment by petersmithca** [comment]
Ok ill look at implementing in other windows too

**Comment by WebCrew** [comment]
wow that would be cool peter, take Your time we have all the time in the world :)

**Comment by petersmithca** [comment]
I've pushed a new commit that should take care of this issue now.  As well, the chat widget now appears on profile and spaces thanks to @WebCrew styling changes!

**Comment by WebCrew** [comment]
Cool Peter thank You -have You already tested it if my style fits the screen resolutions on smaller panels? I hope its working, if not I do my best next days to get it done 100%.

**Comment by petersmithca** [comment]
No, I haven't but for me the side bar disappears on smaller panels anyway?
I don't currently have access to anything but my phone, and the sidebar
disappears there.

**Comment by WebCrew** [comment]
Ahh ok I think its a wanted feature of HumHub, that smaller panels on smaller screens become invisible. Normaly they should only become stored under the main panels. Maybe HumHub team will work it out at a later time.

**Comment by Felli** [comment]
This is now fixed! So this can be closed. :smile:
